name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5 # Version 5 est plus r√©cente et stable
      with:
        python-version: "3.11.9"
        cache: 'pip' # Optimise le temps de run en cachant les libs

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint
        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
        # python -m pylint src/ tests/ --rcfile=.pylintrc
        python -m pylint src/ tests/ --fail-under=7.0


    - name: Analysing the code with pylint
      run: |
        # pylint $(git ls-files '*.py') --fail-under=7.0 --ignore=.venv --disable=C,W
        python -m pylint src/ tests/ --fail-under=7.0 --disable=C,W
        